<?php

namespace RValin\MigrationBundle\Repository;

/**
 * RValinMigrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RValinMigrationRepository extends \Doctrine\ORM\EntityRepository
{
}
